# Generated by Django 4.2.3 on 2023-07-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masina', models.CharField(max_length=1000, unique=True)),
                ('descriere', models.CharField(max_length=2000)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca_masina', models.CharField(choices=[('volkswagen', 'Volkswagen'), ('skoda', 'Skoda'), ('audi', 'Audi'), ('bmw', 'Bmw'), ('mercedes', 'Mercedes'), ('tesla', 'Tesla')], max_length=200)),
                ('stare', models.IntegerField(choices=[(0, 'Indisponibil'), (1, 'Disponibil')], default=1)),
                ('data_crearii', models.DateTimeField(auto_now_add=True)),
                ('data_actualizarii', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
